2025-05-23 20:08:58,028 - __main__ - INFO - Старт приложения
2025-05-23 20:08:58,030 - __main__ - INFO - Запуск бота...
2025-05-23 20:08:58,030 - __main__ - ERROR - Ошибка при запуске бота: Token is invalid!
Traceback (most recent call last):
  File "C:\dev\Aisha_bot_new\app\main.py", line 91, in <module>
    asyncio.run(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\dev\Aisha_bot_new\app\main.py", line 42, in main
    bot = Bot(token=settings.TELEGRAM_TOKEN)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Aisha_bot_new\.venv\Lib\site-packages\aiogram\client\bot.py", line 266, in __init__
    validate_token(token)
  File "C:\dev\Aisha_bot_new\.venv\Lib\site-packages\aiogram\utils\token.py", line 27, in validate_token
    raise TokenValidationError("Token is invalid!")
aiogram.utils.token.TokenValidationError: Token is invalid!
